---
# Easy deployment homeassistant from your own Git
# We copy the whole docker compose files, the directory already exists
# I will improve it later

- name: Set a app variable
  ansible.builtin.set_fact:
    app: "home-assistant"
    app_name: "Home Assistant"

- name: Configuration {{ app_name }}
  block:
  - name: Include config tasks
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/config.yaml"

  # Start the application 
  - name: Create and start {{ app_name }}
    community.docker.docker_compose_v2:
      project_src: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}    

  when: 
    - docker_homeassistant == true
