---
# Monitoring Prometheus with Grafana
- name: Deploy Prometheus
  block:

  - name: Set a app variable
    ansible.builtin.set_fact:
      app: "prometheus"
      app_name: "Prometheus"

  - name: Git clone {{ app_name }}
    ansible.builtin.git:
      repo: 'https://github.com/hufhend/prometheus.git'
      dest: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
      force: true

  - name: Create a directory structure
    ansible.builtin.command: sh init.sh
    args:
      chdir: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}

  - name: Include config tasks
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/config.yaml"     

when: prometheus == true