---
# Monitoring Prometheus with Grafana
- name: Set a app variable
  ansible.builtin.set_fact:
    app: "prometheus"
    app_name: "Prometheus"

- name: Check if {{ app_name }} exists
  ansible.builtin.stat:
    path: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
  register: prometheus_dir_check

- name: Deploy {{ app_name }}
  block:
  - name: Git clone {{ app_name }}
    ansible.builtin.git:
      repo: 'https://github.com/hufhend/prometheus.git'
      dest: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
      force: true

  - name: Create a directory structure
    ansible.builtin.command: sh init.sh
    args:
      chdir: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}

  when: 
    - prometheus == true
    - not prometheus_dir_check.stat.exists

# Update the configuration at every run
- name: Set reset variable
  ansible.builtin.set_fact:
    reset: true
    
- name: Configuration {{ app_name }}
  block:
  - name: Include config tasks
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/config.yaml"

  - name: Change ownership of Grafana directory
    ansible.builtin.file:
      path: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}/grafana/{{ grafana_item }}
      owner: 472
      group: root
      mode: '0755'
      recurse: yes
    loop:
      - etc
      - data
    loop_control:
      loop_var: grafana_item

    become: true
    become_user: root   

  when: 
    - prometheus == true
