---
# Self-hosted Git service
- name: Set a app variable
  ansible.builtin.set_fact:
    app: "openvpn"
    app_name: "OpenVPN"

- name: Deploy {{ app_name }}
  block:
    - name: Git clone {{ app_name }}
      ansible.builtin.git:
        repo: 'https://github.com/hufhend/openvpn.git'
        dest: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
        force: true

    - name: Change ownership of {{ app_name }} directory
      ansible.builtin.file:
        path: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}/data/conf
        owner: "{{ docker_user }}"
        mode: '0750'
        state: directory

    - name: Configuration {{ app_name }}
      block:
      - name: Include config tasks
        ansible.builtin.include_tasks: "{{ role_path }}/tasks/config.yaml"

    - name: Create and start {{ app_name }}
      community.docker.docker_compose_v2:
        project_src: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
  when: openvpn == true
