---
# Self-hosted DNS service
- name: Deploy Pi-hole
  block:

  - name: Set a app variable
    ansible.builtin.set_fact:
      app: "pi-hole"
      app_name: "Pi-hole"

  - name: Check if {{ app_name }} exists
    ansible.builtin.stat:
      path: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
    register: pihole_dir_check

  - name: Build {{ app_name }} on OrangePi
    block:
      - name: Disable DNSStubListener
        ansible.builtin.lineinfile:
          path: /etc/systemd/resolved.conf
          regexp: '^#?DNSStubListener='
          line: 'DNSStubListener=no'
          backrefs: yes
        become: true
        become_user: root

      - name: Remove resolv.conf symlink
        ansible.builtin.file:
          path: /etc/resolv.conf
          state: absent
        become: true
        become_user: root      

      - name: Create symlink to resolv.conf
        ansible.builtin.file:
          src: /run/systemd/resolve/resolv.conf
          dest: /etc/resolv.conf
          state: link
        become: true
        become_user: root

      - name: Restart systemd-resolved
        ansible.builtin.systemd:
          name: systemd-resolved
          state: restarted
        become: true
        become_user: root

      - name: Git clone {{ app_name }}
        ansible.builtin.git:
          repo: 'https://gitlab.torproject.org/hufhendr/pi-hole.git'
          dest: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
          force: true

      - name: Create a directory structure
        ansible.builtin.command: sh init.sh
        args:
          chdir: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}

      - name: Include config tasks
        ansible.builtin.include_tasks: "{{ role_path }}/tasks/config.yaml"

      - name: Find existing netplan files
        ansible.builtin.find:
          paths: /etc/netplan
          patterns: "*"
          file_type: file
        register: netplan_files

      - name: Rename existing netplan files
        ansible.builtin.command:
          cmd: mv "{{ netplan_file.path }}" "{{ netplan_file.path }}.bak"
        loop: "{{ netplan_files.files }}"
        loop_control:
          loop_var: netplan_file
        become: true
        become_user: root

      # - name: Set DNS server to Docker Pi-hole
      #   community.general.nmcli:
      #     conn_name: "{{ ansible_default_ipv4.interface }}"
      #     type: "{{ 'ethernet' if ansible_default_ipv4.type == 'ether' else ansible_default_ipv4.type }}"
      #     dns4:
      #     - 127.0.0.1
      #     state: present
      #   become: true
      #   become_user: root 
      #   # notify: Restart NetworkManager

      # - name: Ignore automatically configured DNS
      #   community.general.nmcli:
      #     conn_name: "{{ ansible_default_ipv4.interface }}"
      #     type: "{{ 'ethernet' if ansible_default_ipv4.type == 'ether' else ansible_default_ipv4.type }}"
      #     dns4_ignore_auto: true
      #     state: present
      #   # notify: Restart NetworkManager

      - name: Upload the netplan template
        ansible.builtin.template:
          src: templates/ansible_pihole.j2
          dest: "/etc/netplan/ansible-pihole.yaml"
          owner: root
          group: root
          mode: '0600'
        become: true
        become_user: root 
        notify: Apply netplan configuration

      # - name: Remove default nameserver
      #   ansible.builtin.lineinfile:
      #     path: /etc/resolv.conf
      #     state: absent
      #     regexp: '^nameserver 1\.0\.0\.1$'
      #   become: true
      #   become_user: root      

    when: not pihole_dir_check.stat.exists
  when: pihole == true