---
#  We expect a full deployment in the private repository

- name: Set a app variable
  ansible.builtin.set_fact:
    app: "rancher"
    app_name: "Rancher"

- name: Configuration {{ app_name }}
  block:
  - name: Include config tasks
    ansible.builtin.include_tasks: "{{ role_path }}/tasks/config.yaml"

  # Start the application
  - name: Create and start {{ app_name }}
    community.docker.docker_compose_v2:
      project_src: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}

  when:
    - docker_rancher == true
