---
#   **************************************
#   Ansible Azure main role - Ubuntu 24.04
#   begin     : Wed 26 Mar 2025
#   copyright : (c) 2025 Václav Dvorský
#   email     : hufhendr@gmail.com
#   $Id: azure.yaml, v1.10 02/04/2025
#   **************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

#   This role is used to manage resources in the Azure Arc cloud and is not 
#   and probably will not be optimized for running in Ansible Tower.

#   Usage:
#   You must create your own set of variables and then:
#   ansible-playbook azure.yml -e "@secrets/cluster_vars.yml"

- name: Call the deploy task
  include_tasks: deploy.yaml
  tags:
  - deploy
  when: "'deploy' in ansible_run_tags"

- name: Call the upgrade task
  include_tasks: upgrade.yaml
  tags:
  - upgrade
  when: "'upgrade' in ansible_run_tags"

- name: Call the delete task
  include_tasks: delete.yaml
  tags:
  - delete
  when: "'delete' in ansible_run_tags"