---
# Ansible for control node
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "ansible"
    app_name: "Ansible"

- name: Install {{ app_name }}
  block:
  - name: Add {{ app_name }} repository
    apt_repository:
      repo: ppa:ansible/ansible
      state: present
      update_cache: yes

  - name: Install {{ app_name }}
    apt:
      name: ansible
      state: present
      update_cache: yes
  when: ansible == True
