---
# Lutris is an Open Source gaming platform for Linux
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "datovka"
    app_name: "Datovka"

- name: Install {{ app_name }}
  block:
  - name: Add {{ app_name }} GPG key
    ansible.builtin.apt_key:
      url: https://download.opensuse.org/repositories/home:CZ-NIC:datovka-latest/xUbuntu_24.04/Release.key
      keyring: /usr/share/keyrings/datovka.gpg
      state: present
  
  - name: Add {{ app_name }} repository
    ansible.builtin.apt_repository:
      repo:  deb [signed-by=/usr/share/keyrings/datovka.gpg] http://download.opensuse.org/repositories/home:/CZ-NIC:/datovka-latest/xUbuntu_24.04/ /
      state: present
      filename: datovka

  - name: Install {{ app_name }}
    ansible.builtin.apt:
      name: datovka
      state: present
  when: datovka == True
