---
# Steam Game platform
# It then installs to the user's home and automatically watches for updates
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "steam"
    app_name: "Steam"

- name: Install {{ app_name }}
  ansible.builtin.apt:
    pkg: steam
    state: present
  when: steam == True
