# Steam Game platform
# It then installs to the user's home and automatically watches for updates
- name: Set a app variable
  ansible.builtin.set_fact:
    app: "steam"
    app_name: "Steam"

- name: Install {{ app_name }}
  block:
  - name: Download Steam package
    ansible.builtin.get_url:
      url: https://cdn.akamai.steamstatic.com/client/installer/steam.deb
      dest: /home/{{ user_ansible }}/install/steam.deb

  - name: Install {{ app_name }}
    ansible.builtin.apt:
      deb: /home/{{ user_ansible }}/install/steam.deb
      state: present
  when: steam == True
