# Vagrant by HashiCorp
- name: Vagrant Variable Setting
  ansible.builtin.set_fact:
    app: "vagrant"
    app_name: "Vagrant"

- name: Install {{ app_name }}
  block:
    - name: Add {{ app_name }} repository
      ansible.builtin.deb822_repository:
        name: hashicorp
        types: deb
        uris: https://apt.releases.hashicorp.com
        suites: "{{ ansible_facts['distribution_release'] }}"
        components: main
        architectures: amd64
        signed_by: https://apt.releases.hashicorp.com/gpg
        state: present
        enabled: true

    - name: Install {{ app_name }}
      ansible.builtin.apt:
        name: vagrant
        state: present
        update_cache: true
  when: vagrant | default(false) | bool
