---
#   *************************************
#   Ansible Azure playbook - Ubuntu 24.04
#   begin     : Wed 26 Mar 2025
#   copyright : (c) 2025 Václav Dvorský
#   email     : hufhendr@gmail.com
#   $Id: azure.yaml, v1.00 26/03/2025
#   *************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

- name: Resource management in Azure cloud
  hosts: localhost
  gather_facts: no  
  roles:
    - role: azure
