---
#   ***************************************
#   Ansible Desktop playbook - Ubuntu 24.04
#   begin     : Tue 7 May 2024
#   copyright : (c) 2024 Václav Dvorský
#   email     : hufhendr@gmail.com
#   $Id: desktop.yaml, v1.22 19/02/2026
#   ***************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

- name: Set up a desktop operating system
  hosts: all
  become: true
  become_user: root
  roles:
    - role: env_settings
    - role: system_upgrade
    - role: docker
    - role: firewall
    - role: desktop
    - role: crontab
    - role: binenv
    - role: cloud_tools
  # environment:
  #   LC_ALL: en_US.UTF-8
  #   LANG: en_US.UTF-8
  #   LANGUAGE: en_US.UTF-8