---
#   ***************************************
#   Ansible Playbook for deploy Docker apps
#   begin     : Thu 27 Jun 2024
#   copyright : (c) 2024 Václav Dvorský
#   email     : Vaclav.Dvorsky@aricoma.com
#   $Id: docker_apps.yaml, v1.00 28/06/2024
#   ***************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

- name: Deploy containerized apps via Docker
  hosts: all
  become: true
  become_user: "{{ docker_user }}"
  roles:
    - role: docker_apps
      # become: true
      # become_user: "{{ docker_user }}"
