---
#   *******************************************
#   Ansible K8s cluster playbook - Ubuntu 22.04
#   begin     : Sat 20 Apr 2024
#   copyright : (c) 2024 Václav Dvorský
#   email     : hufhendr@gmail.com
#   $Id: K8s_cluster.yaml, v1.00 21/04/2024
#   *******************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

#   This playbook prepares Ubuntu machines for roles in a Kubernetes cluster.
#   The Kubernetes installation is then via kubespray.

- hosts: all
  become: true
  roles:
    - role: system_upgrade
    - role: env_settings
    - role: firewall
    - role: cluster_node

