---
#   *******************************************
#   Ansible Orange Pi playbook - Armbian 24.5.0
#   begin     : Fri 29 Mar 2024
#   copyright : (c) 2024 Václav Dvorský
#   email     : hufhendr@gmail.com
#   $Id: orangepi.yaml, v1.02 14/06/2025
#   *******************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

- name: Setting up and updating the operating system
  hosts: all
  become: true
  roles:
  - role: system_upgrade
  - role: env_settings
  - role: docker
  - role: orangepi
  - role: crontab
  - role: firewall
  - role: docker-apps
    become: true
    become_user: "{{ docker_user }}"
  vars:
    ansible_user: hufhendr
