---
#   *******************************************
#   Ansible Orange Pi playbook - Armbian 24.5.0
#   begin     : Fri 29 Mar 2024
#   copyright : (c) 2024 Václav Dvorský
#   email     : vaclav.dvorsky@dataforce.cz
#   $Id: orangepi.yaml, v1.00 30/03/2024
#   *******************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

- name: Setting up and updating the operating system
  hosts: all
  become: true
  roles:
    - role: system_upgrade
    - role: env_settings
    - role: docker
    - role: firewall
    - role: orangepi
    - role: docker_apps
      become: true
      become_user: "{{ docker_user }}"
  vars:
    swap_file: swapfile
    swap_path: "" # empty for root
    swap_size: 3.5G
    ansible_user: hufhendr