- name: Test import _cffi_backend
  hosts: tp01.kn.akira.cz
  tasks:
    - command: python3.13 -c "import _cffi_backend"
      register: result
      ignore_errors: yes

    - debug:
        var: result