---
# Help playbook for solving ad hoc tasks
- hosts: all
  become: true
  tasks:
  # - name: Disable service gdm
  #   ansible.builtin.systemd_service:
  #     name: gdm
  #     enabled: true

  # vars:
  #   container_count: 4
  #   default_container_name: docker
  #   default_container_image: ubuntu
  #   default_container_command: sleep 1d

  # roles:
  #   - role: docker

  - name: Find location of kubectl binary
    find:
      paths: /usr
      patterns: kubectl
      recurse: true
      file_type: any
    register: kubectl_files

  - name: Print found locations of kubectl binary
    debug:
      msg: "kubectl binary found at location {{ item.path }}"
    loop: "{{ kubectl_files.files }}"