---
#   ***************************************
#   Ansible Playbook for Linux setup
#   begin     : Fri 29 Mar 2024
#   copyright : (c) 2024 Václav Dvorský
#   email     : vaclav.dvorsky@dataforce.cz
#   $Id: setup.yaml, v1.00 30/03/2024
#   ***************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

- name: Setting up and updating the operating system
  hosts: all
  become: true
  roles:
    - role: system_upgrade
    - role: env_settings
    - role: firewall

    # # For special cases only
    # - role: docker_apps
    #   become: true
    #   become_user: "{{ docker_user }}"
