---
#   ***************************************
#   Ansible Playbook for Linux setup
#   begin     : Fri 29 Mar 2024
#   copyright : (c) 2024 Václav Dvorský
#   email     : hufhendr@gmail.com
#   $Id: setup.yaml, v1.10 06/11/2025
#   ***************************************

#   --------------------------------------------------------------------
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public Licence as published by
#   the Free Software Foundation; either version 2 of the Licence, or
#   (at your option) any later version.
#   --------------------------------------------------------------------

- name: Setting up and updating the operating system
  hosts: all
  become: true
  roles:
    - role: env_settings
    - role: system_upgrade
    - role: firewall
