# A simple, modern and secure encryption tool
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "age"
    app_name: "Age"
    app_dir: "/usr/local/bin"

- name: Install {{ app_name }}
  block:
  - name: Install {{ app_name }}
    command: "{{ app_dir }}/binenv install {{ app }}"
    args:
      creates: "{{ app_dir }}/{{ app }}"  

  - name: Install {{ app }}-keygen
    command: "{{ app_dir }}/binenv install {{ app }}-keygen"
    args:
      creates: "{{ app_dir }}/{{ app }}-keygen"  

  - name: Check {{ app_name }} version
    command: "{{ app_dir }}/{{ app }} --version"
    register: "install_result"
    changed_when: false
    become_user: "{{ ansible_user }}"
    ignore_errors: true

  - name: Show {{ app_name }} version
    debug:
      msg: "{{ install_result.stdout }}"
    ignore_errors: true

  when: age and (binenv | default(false))
