# Microsoft Azure CLI on Linux
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "azcli"
    app_name: "Azure CLI"

- name: Install {{ app_name }} on Linux
  block:
  - name: Add Microsoft GPG key
    ansible.builtin.apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      keyring: /usr/share/keyrings/microsoft.gpg
      state: present

  - name: Add {{ app_name }} repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
      state: present
      filename: azure-cli
      
  - name: Install {{ app_name }}
    ansible.builtin.apt:
      name: azure-cli=2.69*
      state: present
      allow_downgrade: true

  - name: Check {{ app_name }} version
    command: "/usr/bin/az version -o json"
    register: "install_result"
    changed_when: false
    become_user: "{{ ansible_user }}"
    ignore_errors: true

  - name: Show {{ app_name }} version
    debug:
      msg: "{{ install_result.stdout | from_json }}"

  - name: Hold {{ app_name }} to prevent upgrades
    ansible.builtin.command:
      cmd: apt-mark hold azure-cli
    changed_when: false

  when: azcli == True
