# buildx is a Docker CLI plugin for extended build capabilities with BuildKit
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "buildx"
    app_name: "Buildx plugin"

- name: Install {{ app_name}}
  block:
  - name: Install {{ app_name }}
    command: "{{ app_dir }}/binenv install {{ app }}"
    args:
      creates: "{{ app_dir }}/{{ app }}"

  # Completion script tasks
  - name: Check if completion script exists
    stat:
      path: "/etc/bash_completion.d/{{ app }}"
    register: completion_script_stat

  - name: Generate completion script
    command: "{{ app_dir }}/{{ app }} completion bash"
    register: completion_script
    changed_when: false
    when: not completion_script_stat.stat.exists

  - name: Save completion script
    copy:
      content: "{{ completion_script.stdout }}"
      dest: "/etc/bash_completion.d/{{ app }}"
      mode: "0644"
    when: not completion_script_stat.stat.exists

  # Show installed version
  - name: Check {{ app_name }} version
    command: "{{ app_dir }}/{{ app }} version"
    register: "install_result"
    changed_when: false
    ignore_errors: true

  - name: Extract and clean version
    set_fact:
      new_version: "{{ (install_result.stdout | regex_search('v?([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1')) | first }}"

  - name: Show {{ app_name }} version
    ansible.builtin.debug:
      msg: "{{ app_name }} version is {{ new_version }}"

    when: buildx and (binenv | default(false))
