# K9s is a terminal based UI to interact with your Kubernetes clusters
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "k9s"
    app_name: "K9s"

- name: Install {{ app_name}}
  block:
  - name: Install {{ app_name }}
    command: "{{ app_dir }}/binenv install {{ app }}"
    args:
      creates: "{{ app_dir }}/{{ app }}"

  # Generate completion script
  - name: Check if completion script exists
    stat:
      path: "/etc/bash_completion.d/{{ app }}"
    register: completion_script_stat

  - name: Generate completion script
    command: "{{ app_dir }}/{{ app }} completion bash"
    register: completion_script
    changed_when: false
    when: not completion_script_stat.stat.exists

  - name: Save completion script
    copy:
      content: "{{ completion_script.stdout }}"
      dest: "/etc/bash_completion.d/{{ app }}"
      mode: "0644"
    when: not completion_script_stat.stat.exists

  # Show installed version
  - name: Check {{ app_name }} version
    command: "{{ app_dir }}/{{ app }} version"
    register: "install_result"
    changed_when: false

  - name: Extract and clean version
    set_fact:
      new_version: "{{ (install_result.stdout | regex_replace('\\x1b\\[[0-9;]*m', '') | regex_search('Version:\\s*v([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1')) | first }}"

  - name: Show {{ app_name }} version
    debug:
      msg: "{{ app_name }} version is {{ new_version }}"

  when: k9s and (binenv | default(false))
