# utility to switch between K8s namespaces
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "kubens"
    app_name: "kubens"
    app_dir: "/usr/local/bin"    

- name: Install {{ app_name}}
  block:
  - name: Install {{ app_name }}
    command: "{{ app_dir }}/binenv install {{ app }}"
    args:
      creates: "{{ app_dir }}/{{ app }}"

  - name: Check {{ app_name }} version
    command: "{{ app_dir }}/{{ app }} --version"
    register: "install_result"
    changed_when: false
    become_user: "{{ ansible_user }}"
    ignore_errors: true

  - name: Show {{ app_name }} version
    debug:
      msg: "{{ install_result.stdout.split('\n') }}"

  when: kubens and (binenv | default(false))
