# utility to switch between K8s namespaces
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "kubens"
    app_name: "Kubens"

- name: Install {{ app_name}}
  block:
  - name: Install {{ app_name }}
    command: "{{ app_dir }}/binenv install {{ app }}"
    args:
      creates: "{{ app_dir }}/{{ app }}"

  - name: Check {{ app_name }} version
    command: "{{ app_dir }}/{{ app }} --version"
    register: "install_result"
    changed_when: false

  - name: Show {{ app_name }} version
    ansible.builtin.debug:
      msg: "{{ app_name }} version is {{ install_result.stdout }}"

  when: kubens and (binenv | default(false))
