---
# Creates OpenShift clusters
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "openshift-install"
    app_name: "OpenShift installer"
    app_dir: "/usr/local/bin"
    install_dir: "/home/{{ user_ansible }}/install"
    version: "4.19.13"

# Download and verification steps
- name: Download {{ app_name }} checksum
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/sha256sum.txt
    dest: "{{ install_dir }}/sha256sum.txt"
    mode: '0644'
    force: yes

- name: Download SHA256 signature file
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/sha256sum.txt.gpg
    dest: "{{ install_dir }}/sha256sum.txt.gpg"
    mode: '0644'
    force: yes

- name: Download GPG public key
  ansible.builtin.command:
    cmd: gpg --recv-keys 199E2F91FD431D51

- name: Verify GPG signature 
  ansible.builtin.command:
    cmd: gpg --verify {{ install_dir }}/sha256sum.txt.gpg
  register: gpg_verify_result
  failed_when: gpg_verify_result.rc != 0    

- name: Download openshift-install archive
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux-{{ version }}.tar.gz
    dest: "{{ install_dir }}/openshift-install-linux-{{ version }}.tar.gz"
    mode: '0644'

- name: Verify checksum of {{ app_name }} 
  ansible.builtin.command:
    cmd: sha256sum -c {{ install_dir }}/sha256sum.txt --ignore-missing
    chdir: "{{ install_dir }}"
  register: checksum_result
  failed_when: "'FAILED' in checksum_result.stdout"

# Manual installation of a binary application
- name: Show checksum verification
  ansible.builtin.debug:
    msg: "{{ checksum_result.stdout_lines | select('search', app) | list }}"

- name: Install {{ app_name }}
  block:
  - name: Extract {{ app_name }} archive
    ansible.builtin.unarchive:
      src: "{{ install_dir }}/openshift-install-linux-{{ version }}.tar.gz"
      dest: "{{ install_dir }}"
      remote_src: yes

  - name: Move {{ app }} to local bin
    ansible.builtin.copy:
      src: "{{ install_dir }}/openshift-install"
      dest: "{{ app_dir }}/openshift-install"
      mode: '0755'
      remote_src: yes

  # Completion script tasks
  - name: Check if completion script exists
    stat:
      path: "/etc/bash_completion.d/{{ app }}"
    register: completion_script_stat

  - name: Generate completion script
    command: "{{ app_dir }}/{{ app }} completion bash"
    register: completion_script
    changed_when: false
    when: not completion_script_stat.stat.exists

  - name: Save completion script
    copy:
      content: "{{ completion_script.stdout }}"
      dest: "/etc/bash_completion.d/{{ app }}"
      mode: "0644"
    when: not completion_script_stat.stat.exists

  # Show installed version
  - name: Verify {{ app_name }} version
    ansible.builtin.command: "{{ app_dir }}/{{ app }} version"
    register: oc_version_output
    changed_when: false

  - name: Show {{ app_name }} version
    ansible.builtin.debug:
      msg: "{{ oc_version_output.stdout }}"

  when: ocpinstall == True
