---
# Python via DeadSnakes repo
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "python3"
    app_name: "Python"

- name: Install {{ app_name }}
  block:
  - name: Add DeadSnakes GPG key
    ansible.builtin.apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF23C5A6CF475977595C89F51BA6932366A755776
      keyring: /usr/share/keyrings/deadsnakes.gpg
      state: present

  - name: Add {{ app_name }} repository
    ansible.builtin.apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/deadsnakes.gpg] https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu/ {{ ansible_distribution_release }} main
      state: present
      filename: python

  - name: Install {{ app_name }}
    ansible.builtin.apt:
      name: "{{ app }}"
      state: present

  when: 
    - python == True
    - ansible_distribution == "Ubuntu"

# Show installed version
- name: Verify {{ app_name }} version
  ansible.builtin.command: "/usr/bin/{{ app }} --version"
  register: install_result
  changed_when: false

- name: Extract and clean version
  set_fact:
    python_version: "{{ install_result.stdout | regex_search('Python ([\\d.]+)', '\\1') | first }}"

- name: Show {{ app_name }} version
  ansible.builtin.debug:
    msg: "{{ app_name }} version is {{ python_version }}"
