# Login and retrieve AWS temporary credentials using a SAML IDP
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "saml2aws"
    app_name: "saml2aws tool"
    app_dir: "/usr/local/bin"

- name: Install {{ app_name}}
  block:
  - name: Install {{ app_name }}
    command: "{{ app_dir }}/binenv install {{ app }}"
    args:
      creates: "{{ app_dir }}/{{ app }}"

  when: saml2aws and (binenv | default(false))
