# Starship is the minimal, blazing fast, and extremely customizable prompt for any shell
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "starship"
    app_name: "Starship"

- name: Install {{ app_name}}
  block:
  - name: Install {{ app_name }}
    command: "{{ app_dir }}/binenv install {{ app }}"
    args:
      creates: "{{ app_dir }}/{{ app }}"

  # Generate completion script
  - name: Check if completion script exists
    stat:
      path: "/etc/bash_completion.d/{{ app }}"
    register: completion_script_stat

  - name: Generate completion script
    command: "{{ app_dir }}/{{ app }} completions bash"
    register: completion_script
    changed_when: false
    when: not completion_script_stat.stat.exists

  - name: Save completion script
    copy:
      content: "{{ completion_script.stdout }}"
      dest: "/etc/bash_completion.d/{{ app }}"
      mode: "0644"
    when: not completion_script_stat.stat.exists

  # Show installed version
  - name: Check {{ app_name }} version
    command: "{{ app_dir }}/{{ app }} --version"
    register: "install_result"
    changed_when: false

  - name: Extract and clean version
    set_fact:
      new_version: "{{ (install_result.stdout | regex_search('starship ([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1')) | first }}"

  - name: Show {{ app_name }} version
    debug:
      msg: "{{ app_name }} version is {{ new_version }}"

  # Enable starship in bashrc and skeleton
  - name: Add {{ app_name }} config to .bashrc
    ansible.builtin.lineinfile:
      path: /home/{{ user_ansible }}/.bashrc
      line: 'export STARSHIP_CONFIG=~/.config/starship.toml'
      insertafter: EOF
      create: yes
      state: present

  - name: Add {{ app_name }} init to .bashrc
    ansible.builtin.lineinfile:
      path: /home/{{ user_ansible }}/.bashrc
      line: 'eval "$(starship init bash)"'
      insertafter: EOF
      create: yes
      state: present

  - name: Add {{ app_name }} config to skeleton
    ansible.builtin.lineinfile:
      path: /etc/skel/.bashrc
      line: 'export STARSHIP_CONFIG=~/.config/starship.toml'
      insertafter: EOF
      create: yes
      state: present

  - name: Add {{ app_name }} init to skeleton
    ansible.builtin.lineinfile:
      path: /etc/skel/.bashrc
      line: 'eval "$(starship init bash)"'
      insertafter: EOF
      create: yes
      state: present

  when: starship and (binenv | default(false))
