# Starship is the minimal, blazing fast, and extremely customizable prompt for any shell
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "starship"
    app_name: "Starship"
    app_dir: "/usr/local/bin"

- name: Install {{ app_name}}
  block:
  - name: Install {{ app_name }}
    command: "{{ app_dir }}/binenv install {{ app }}"
    args:
      creates: "{{ app_dir }}/{{ app }}"

  - name: Check if completion script exists
    stat:
      path: "/etc/bash_completion.d/{{ app }}"
    register: completion_script_stat

  - name: Generate completion script
    command: "{{ app_dir }}/{{ app }} completions bash"
    register: completion_script
    changed_when: false
    when: not completion_script_stat.stat.exists

  - name: Save completion script
    copy:
      content: "{{ completion_script.stdout }}"
      dest: "/etc/bash_completion.d/{{ app }}"
      mode: "0644"
    when: not completion_script_stat.stat.exists

  - name: Check {{ app_name }} version
    command: "{{ app_dir }}/{{ app }} --version"
    register: "install_result"
    changed_when: false
    ignore_errors: true

  - name: Show {{ app_name }} version
    debug:
      msg: "{{ install_result.stdout.split('\n') }}"

  when: starship and (binenv | default(false))
