# Terraform is an IaC tool
---
- name: Terraform Variable Setting
  ansible.builtin.set_fact:
    app: "terraform"
    app_name: "Terraform"

- name: Install {{ app_name }}
  block:
    - name: Add {{ app_name }} repository
      ansible.builtin.deb822_repository:
        name: hashicorp
        types: deb
        uris: https://apt.releases.hashicorp.com
        suites: "{{ ansible_facts['distribution_release'] }}"
        components: main
        architectures: amd64
        signed_by: https://apt.releases.hashicorp.com/gpg
        state: present
        enabled: true

    - name: Install {{ app_name }}
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: true

    - name: Add {{ app_name }} autocomplete
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: "complete -C /usr/bin/terraform terraform"
        state: present
        create: true
        mode: "0644"
      become_user: "{{ ansible_user }}"

    - name: Check {{ app_name }} version
      ansible.builtin.command:
        cmd: "/usr/bin/{{ app }} version"
      register: install_result
      changed_when: false
      become_user: "{{ ansible_user }}"
      ignore_errors: true

    - name: Extract and clean {{ app_name }} version
      ansible.builtin.set_fact:
        new_version: "{{ (install_result.stdout | regex_search('Terraform v?([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1')) | first }}"

    - name: Show {{ app_name }} version
      ansible.builtin.debug:
        msg: "{{ app_name }} version is {{ new_version }}"

  when:
    - terraform | default(false) | bool
    - ansible_facts["distribution"] == "Ubuntu"
