# Terraform is an IaC tool
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "terraform"
    app_name: "Terraform"

- name: Install {{ app_name }}
  block:
  - name: Add {{ app_name }} GPG key
    ansible.builtin.apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
      state: present

  - name: Add {{ app_name }} repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
      state: present
      filename: hashicorp

  - name: Install {{ app_name }}
    ansible.builtin.apt:
      name: terraform
      state: present

  - name: Add {{ app_name}} autocomplete
    ansible.builtin.lineinfile:
      path: "/home/{{ ansible_user }}/.bashrc"
      line: "complete -C /usr/bin/terraform terraform"
      state: present
      create: yes
      mode: '0644'
    become_user: "{{ ansible_user }}"

  - name: Check {{ app_name }} version
    command: "/usr/bin/{{ app }} version"
    register: "install_result"
    changed_when: false
    become_user: "{{ ansible_user }}"
    ignore_errors: true

  - name: Show {{ app_name }} version
    debug:
      msg: "{{ install_result.stdout.split('\n') }}"

  when: 
    - terraform == True
    - ansible_distribution == "Ubuntu"
