# Terraform is an IaC tool
---
- name: Package Variable Setting
  ansible.builtin.set_fact:
    app: "terraform"
    app_name: "Terraform"

- name: Install {{ app_name}}
  block:
  - name: Install {{ app_name }}
    command: /usr/local/bin/binenv install {{ app }}
    args:
      creates: "/usr/local/bin/{{ app }}"

  - name: Install completion script
    command: terraform -install-autocomplete

  - name: Check {{ app_name }} version
    command: "/usr/local/bin/{{ app }} version"
    register: "install_result"
    changed_when: false
    become_user: "{{ ansible_user }}"
    ignore_errors: true

  - name: Show {{ app_name }} version
    debug:
      msg: "{{ install_result.stdout.split('\n') }}"

  when: terraform and (binenv | default(false))   
