# Trivy to find vulnerabilities (CVE) & misconfigurations (IaC) across code repositories
---
- name: Trivy variable setting
  ansible.builtin.set_fact:
    app: "trivy"
    app_name: "Trivy"

- name: Install {{ app_name }}
  when:
    - trivy | default(false) | bool
    - ansible_facts["distribution"] == "Ubuntu"
  block:
    - name: Add {{ app_name }} repository
      ansible.builtin.deb822_repository:
        name: trivy
        types: deb
        uris: https://aquasecurity.github.io/trivy-repo/deb
        suites: generic
        components: main
        signed_by: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present
        enabled: true

    - name: Install {{ app_name }} package
      ansible.builtin.apt:
        name: "{{ app }}"
        state: present

    - name: Check if completion script exists
      ansible.builtin.stat:
        path: "/etc/bash_completion.d/{{ app }}"
      register: completion_script_stat

    - name: Generate completion script
      ansible.builtin.command:
        cmd: "{{ app }} completion bash"
      register: completion_script
      changed_when: false
      when: not completion_script_stat.stat.exists

    - name: Save completion script
      ansible.builtin.copy:
        content: "{{ completion_script.stdout }}"
        dest: "/etc/bash_completion.d/{{ app }}"
        mode: "0644"
      when: not completion_script_stat.stat.exists

    - name: Check {{ app_name }} version
      ansible.builtin.command:
        cmd: "/usr/bin/{{ app }} version"
      register: install_result
      changed_when: false
      failed_when: false

    - name: Extract and clean {{ app_name }} version
      ansible.builtin.set_fact:
        new_version: >-
          {{
            (install_result.stdout | default('')
             | regex_search('Version:\s*v?([0-9]+\.[0-9]+\.[0-9]+)', '\1')
             | first)
            | default('unknown', true)
          }}

    - name: Show {{ app_name }} version
      ansible.builtin.debug:
        msg: "{{ app_name }} version is {{ new_version }}"
