apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/instance: infra-apps
spec:
  acme:
    email: hufhendr@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
    # - dns01:
    #     cloudflare:
    #       email: hufhendr@gmail.com
    #       apiKeySecretRef:
    #         name: cloudflare-api-key-secret
    #         key: api-key
