galaxy_info:
  author: Václav Dvorský
  description: Consultant IT
  company: Data Force

  license: GPL-3.0-or-later

  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: RedHat
      versions:
        - all

  galaxy_tags:
    - system
    - monitoring
    - logging
    - upgrade
    
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
