---
- name: Check repositories
  ansible.builtin.command: apt --fix-broken install --yes

- name: Repair and configure packages
  ansible.builtin.command: sudo dpkg --configure -a

- name: Update repositories
  ansible.builtin.apt:
    state: fixed
    update_cache: true

- name: System upgrade
  ansible.builtin.apt:
    name: "*"
    state: latest
    autoremove: true

- name: Install useful packages
  ansible.builtin.apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - htop
    - screen
    - mc
    - sysstat
    - smartmontools
    - lm-sensors
    - fail2ban
    - open-iscsi
    - nfs-common
    - ethtool
    - prometheus-node-exporter
    - ufw
    - bash-completion
    - bind9-dnsutils

# We delete files created in earlier versions and now obsolete 
- name: Remove specific files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    # - /etc/apt/sources.list.d/hashicorp.list
    - /etc/apt/sources.list.d/google-chrome.sources
    # - /etc/apt/sources.list.d/megasync.list
    - /etc/apt/sources.list.d/vscode.sources
    # - /etc/apt/sources.list.d/docker.list
    - /etc/apt/sources.list.d/google.list
    - /etc/apt/sources.list.d/kubernetes.list
    - /etc/apt/sources.list.d/signal-xenial.list
    - /etc/apt/sources.list.d/vscode-signed.list
    - /etc/apt/sources.list.d/ansible-ubuntu-ansible-jammy.sources
    - /etc/apt/sources.list.d/chrome.list

- name: Find all distUpgrade files
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: "*.distUpgrade"
  register: found_files

- name: Remove found distUpgrade files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ found_files.files }}"    

- name: Enable sysstat service
  ansible.builtin.lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="true"'
    backup: true

- name: Start the sysstat service
  ansible.builtin.systemd:
    name: sysstat
    state: started
    enabled: true

- name: Start the fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Register the system release
  raw: cat /etc/issue
  register: system_release
  changed_when: no
  check_mode: no

- name: Upload a modified sources.list
  copy:
    src: "{{ role_path }}/defaults/sources.list.armbian"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: "'Armbian' in system_release.stdout and 'jammy' in system_release.stdout"

- name: Move node-exporter to port 9101
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-node-exporter
    regexp: '^ARGS='
    line: 'ARGS="--web.listen-address=:9101"'

- name: Restart prometheus-node-exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter.service
    state: restarted
