---
# firewall rules for cluster services
fw_cluster_svc:
  common:
    - { port: 80, comment: 'Allow http' }
    - { port: 443, comment: 'Allow https' }
    - { port: 53, comment: 'Allow DNS' }
    - { port: 53, proto: udp, comment: 'Allow DNS' }
    - { port: 9100, comment: 'Allow Node Exporter (K8s)', from: "{{ safe_network }}" }
    - { port: 80, comment: 'Allow http outbound', route: true, from: "{{ kube_network }}" }
    - { port: 443, comment: 'Allow https outbound', route: true, from: "{{ kube_network }}" }

  master:
    - { port: 2379, comment: 'Allow etcd-client' }
    - { port: 2380, comment: 'Allow etcd-server' }
    - { port: 6443, comment: 'Allow Kubernetes API server' }
    - { port: 7946, comment: 'Allow MetalLB' }
    - { port: 7946, comment: 'Allow MetalLB', proto: udp }
    - { port: 9153, comment: 'Allow CoreDNS metrics' }
    - { port: 9253, comment: 'Allow NodeLocal DNS metrics' }
    - { port: 10250, comment: 'Allow Kubelet API' }
    - { port: 10257, comment: 'Allow kube-controller manager' }
    - { port: 10259, comment: 'Allow kube-scheduler' }
    
  worker:
    - { port: 7946, comment: 'Allow MetalLB' }
    - { port: 7946, comment: 'Allow MetalLB', proto: udp }
    - { port: 9253, comment: 'Allow NodeLocal DNS metrics' }    
    - { port: 10250, comment: 'Allow Kubelet API' }
    - { port: 10256, comment: 'Allow kube-proxy' }
    - { port: 25565, comment: 'Allow Minecraft game' }    
    - { port: "30000:32767", comment: 'Allow NodePort Services' }
