  - name: Create a pods directory
    ansible.builtin.file:
      path: /var/log.hdd/pods
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Ensure old pods is absent
    ansible.builtin.file:
      path: /var/log/pods
      state: absent

  - name: Create link to new pods
    ansible.builtin.file:
      src: /var/log.hdd/pods
      dest: /var/log/pods
      state: link
