- name: Set up crontab for Debian family
  block:
    - name: Add Kubernetes crontab (Debian)
      ansible.builtin.template:
        src: templates/crontab-k8s.j2
        dest: "/var/spool/cron/crontabs/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        group: crontab
        mode: '0600'
      when: role in ['combi', 'master', 'worker']

    - name: Add OrangePi crontab (Debian)
      ansible.builtin.template:
        src: templates/crontab-orange.j2
        dest: "/var/spool/cron/crontabs/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        group: crontab
        mode: '0600'
      when:
        - orange | default(false)
        - role not in ['combi', 'master', 'worker']
  when: ansible_facts["os_family"] == "Debian"

- name: Set up universal crontab
  ansible.builtin.template:
    src: "{{ cron_template | default('templates/crontab-default.j2') }}"
    dest: "/var/spool/cron/{{ 'crontabs/' if ansible_facts['os_family'] == 'Debian' else '' }}{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    group: "{{ 'crontab' if ansible_facts['os_family'] == 'Debian' else ansible_user }}"
    mode: '0600'
  when:
    - cron | default(false)
    - ansible_facts["os_family"] == "RedHat" or
      (ansible_facts["os_family"] == "Debian" and role not in ['combi', 'master', 'worker'] and not (orange | default(false)))