- name: Sets BINENV_GLOBAL in environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^BINENV_GLOBAL='
    line: BINENV_GLOBAL=true

- name: Installs completion in /etc/bash.bashrc
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    regexp: 'binenv completion bash'
    line: "source <(binenv completion bash)"

- name: Add write permission for cache
  ansible.builtin.file:
    path: /var/cache/binenv/cache.json
    state: touch
    mode: '666'