---
- name: Install Docker - containers for applications
  block:
  - name: Install required system packages
    ansible.builtin.apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /etc/apt/trusted.gpg.d/docker.gpg
      state: present

  - name: Add Docker repository
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
      filename: docker

  - name: Install Docker
    ansible.builtin.apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      update_cache: true

  - name: Add current user to docker group
    ansible.builtin.user:
      name: "{{ docker_user }}"
      groups: docker
      append: yes

  when: 
    - role not in ['combi', 'master', 'worker']
    - ansible_os_family | lower == "debian"