---
driver:
  name: docker
platforms:
- name: instance
  image: "geerlingguy/docker-ubuntu2404-ansible"
  pre_build_image: true
provisioner:
  name: ansible
  options:
    roles_path:
    - ../../
dependency:
  name: galaxy
