---
driver:
  name: docker
platforms:
  - name: instance
    image: "ubuntu:latest"
    command: /sbin/init
    privileged: true
    pre_build_image: true
dependency:
  name: galaxy
  options:
    role-name-check: 0
provisioner:
  name: ansible
