---
# Configurations are taken from our own git
- name:  Get {{ app_name }} configuration
  ansible.builtin.git:
    repo: "{{ private_repo }}"
    dest: /tmp/config
    force: true
  ignore_errors: true

- name:  Copy the {{ app_name }} config files
  ansible.builtin.command: sudo rsync -ra /tmp/config/{{ inventory_hostname }}/{{ app }}/ /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
  ignore_errors: true

# Warning: tar archive must be created relatively and error-free
- name: Check if {{ app_name }} Tar config exists
  ansible.builtin.stat:
    path: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}/conf.tgz
  register: config_tar

- name: Config {{ app_name }}
  block:
  - name: Unpack the Tar archive of config files
    ansible.builtin.unarchive:
      src: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}/conf.tgz
      dest: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
      remote_src: yes
    become: true
    become_user: root

  - name: Get checksum of Tar archive
    stat:
      path: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}/conf.tgz
      checksum_algorithm: sha256
      get_checksum: yes
    register: config_tar_sha

  # - name: Read SHA512 checksum from file
  #   slurp:
  #     src: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}/conf.tgz.sha
  #   register: checksum_file

  - name: Read SHA512 sum from file
    command: awk '{print $1}' /home/{{ docker_user }}/{{ docker_home }}/{{ app }}/conf.tgz.sha
    register: expected_checksum

  - name: Debug output for checksums
    debug:
      msg: |
        Vypočítaný hash:      {{ config_tar_sha }}
        Očekávaný hash:       {{ expected_checksum }}
        {% if tar_stat.stat.checksum == expected_checksum %}
        Tyto hodnoty se shodují.
        {% else %}
        Tyto hodnoty se neshodují.
        {% endif %}      

  - name: Verify sha512 sum of the tar file before proceeding
    fail:
      msg: "Checksum does not match. Aborting."
    when: config_tar_sha.stat.checksum != expected_checksum

  - name: Proceed with further tasks if checksum is valid
    debug:
      msg: "Checksum is valid, proceeding with further tasks."    

  - name: Delete Tar temp files
    ansible.builtin.file:
      path: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}/conf.tgz*
      state: absent

  when: 
    - config_tar.stat.exists

- name: Delete temporary files
  ansible.builtin.file:
    path: /tmp/config
    state: absent
  ignore_errors: true

- name: Shut down {{ app_name }} services
  community.docker.docker_compose_v2:
    project_src: /home/{{ docker_user }}/{{ docker_home }}/{{ app }}
    state: absent
  ignore_errors: true

- name:  Delete everything old
  ansible.builtin.command: docker system prune -af --volumes
  when: reset | default(false) == true

# Starting the application is a matter of the application task
