---
- name: Deploying contejnerized applications
  block:
  - name: Create a Docker directory
    ansible.builtin.file:
      path: /home/{{ docker_user }}/{{ docker_home }}
      state: directory
      owner: "{{ docker_user }}"
      group: "{{ docker_user }}"
      mode: '0750'

  #  Back everything up before any changes
  - name: Create a Docker backup directory
    ansible.builtin.file:
      path: /home/{{ docker_user }}/backup/{{ docker_home }}
      state: directory
      owner: "{{ docker_user }}"
      group: "{{ docker_user }}"
      mode: '0750'

  - name:  Back everything up before any changes
    command: sudo rsync -ra --delete /home/{{ docker_user }}/{{ docker_home }}/ /home/{{ docker_user }}/backup/{{ docker_home }}
    become: true
    become_user: root

  # Automated ACME SSL certificate generation for nginx-proxy
  - name: Clone acme-companion in Docker
    block:
      - name: ACME companion Git clone
        ansible.builtin.git:
          repo: 'https://github.com/hufhend/acme-companion.git'
          dest: /home/{{ docker_user }}/{{ docker_home }}/acme-companion

  - name: Create and start ACME services
    community.docker.docker_compose_v2:
      project_src: /home/{{ docker_user }}/{{ docker_home }}/acme-companion
    # register: output

  - name: Add other Docker apps
    include_tasks:
      file: "{{ item }}"
    loop: "{{ query('fileglob', '{{ role_path }}/files/*.yaml') }}"
    no_log: true

  when: role not in ['combi', 'master', 'worker']