name: Ansible Molecule Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario: ["default"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            ansible \
            ansible-lint \
            molecule \
            molecule-docker \
            docker \
            testinfra

      - name: Run Molecule tests
        run: |
          cd roles/docker_apps
          molecule test --scenario-name ${{ matrix.scenario }}
